let Fabrics = [
  "Cotton",
  "Denim",
  "Silk",
  "Natural",
  "Felt",
  "Velvet",
  "Rayon",
  "Wool",
  "Satin",
  "Jacqurd",
  "Chiffon",
  "Bazie",
  "Twill",
  "Dimity",
];

const random = (arr) => arr[Math.floor(Math.random() * arr.length)];

let allProducts = [
  {
    name: "Mandarin Collar Rayon All Over Floral Print Grey A-Line Tunic For Women",
    type: "Women Ethnic",
    id: 1,
    sprice: 165,
    aprice: 950,
    rating: 4.6,
    reviews: 69,
    off: 95,
    img: "https://kalamandir.online/static/media/ff1.5f9b1848a7d649ec0e14.webp",
    details: [
      `Fabric : ${random(Fabrics)}`,
      "Sleeve Length : Three-Quarter Sleeves",
      "Pattern : Embroidered",
      "Combo of : Single",
    ],
  },
  {
    name: "Trendy Pretty Kurtis",
    type: "Women Ethnic",
    id: 2,
    sprice: 410,
    aprice: 460,
    rating: 4.6,
    reviews: 69,
    off: 95,
    img: "https://kalamandir.online/static/media/ee1.9d2bdca8426fcc8b01a5.webp",
    details: [
      `Fabric : ${random(Fabrics)}`,
      "Sleeve Length : Three-Quarter Sleeves",
      "Pattern : Embroidered",
      "Combo of : Single",
    ],
  },
  {
    name: "Trendy Pretty Kurtis",
    type: "Women Ethnic",
    id: 3,
    sprice: 410,
    aprice: 460,
    rating: 4.6,
    reviews: 69,
    off: 95,
    img: "https://images.meesho.com/images/products/41713416/fef4b_512.jpg",
    details: [
      `Fabric: ${random(Fabrics)}`,
      "Sleeve Length: Three-Quarter Sleeves",
      "Pattern: Embroidered",
      "Combo of: Single",
    ],
  },
  {
    name: "Mandarin Collar Muslin All Over Geometric Print Grey Straight Tunic For Women",
    type: "Women Ethnic",
    id: 4,
    sprice: 265,
    aprice: 1020,
    rating: 4.6,
    reviews: 5129,
    off: 95,
    img: "https://kalamandir.online/static/media/hh1.9e9a11318df3e988a166.webp",
    details: [
      `Fabric : ${random(Fabrics)}`,
      "Sleeve Length : Three-Quarter Sleeves",
      "Pattern : Embroidered",
      "Combo of : Single",
    ],
  },
  {
    name: "Mandarin Collar Muslin All Over Geometric Print Grey Straight Tunic For Women",
    type: "Women Ethnic",
    id: 5,
    sprice: 215,
    aprice: 590,
    rating: 4.6,
    reviews: 99,
    off: 95,
    img: "https://kalamandir.online/static/media/gg1.8fcd8a1482debbf5c30a.webp",
    details: [
      `Fabric : ${random(Fabrics)}`,
      "Sleeve Length : Three-Quarter Sleeves",
      "Pattern : Embroidered",
      "Combo of : Single",
    ],
  },
  {
    name: "Mandarin Collar Muslin All Over Geometric Print Grey Straight Tunic For Women",
    type: "Women Ethnic",
    id: 6,
    sprice: 350,
    aprice: 655,
    rating: 4.6,
    reviews: 344,
    off: 95,
    img: "https://kalamandir.online/static/media/ii1.99ec5f2a4ea93f2ea2a1.webp",
    details: [
      `Fabric : ${random(Fabrics)}`,
      "Sleeve Length : Three-Quarter Sleeves",
      "Pattern : Embroidered",
      "Combo of : Single",
    ],
  },
  
];
export { allProducts };
