let Sellers = [
  "The Banarasi Store",
  "SHUBHARAMBH VENTURES",
  "SMART HANDICRAFT",
  "GOOD PRICE STORE",
  "KOTTY LIFESTYLE LIMITED",
  "V King Kohli",
  "Satyasaidata",
  "Shivtrader",
  "Aromatic",
  "happy creation sarees",
  "BANSIWAL ENTERPRISES",
  "Shershaan",
  "Mangalsutras",
  "BRAND PLUS TRADING",
  "Krishna Enterprises",
  "H F WARSI GARMENTS",
  "VISENAFAB",
  "Vanitha Tex",
  "NEW INDIA ENTERPRISES",
  "CRAFTOS HANDICRAFTS",
  "Rudu fashion",
  "Vansh Enterprises",
  "BHARTI TRADING CO.",
  "aditi_fashion",
  "Studio 51 Clothing Co",
  "Bewitched Boutique ",
  "Zalya",
  "Retro Walk",
  "Fashionista ",
  "Dwell check",
  "Finest Stitch",
  "Clean Clothe",
  "Overall",
  "The Strange",
  "Manner Pro",
  "Civilian Costume",
  "The Soft Apparel",
  "DistinctTrends",
  "BrightClothing",
  "RomanFashion check",
  "Magnificent check",
  "The Observed check",
  "Cut Place check",
  "Couture Group check",
  "NeuroticTrends check",
  "Dress Place ",
  "The Contemporary",
  "LightClothing",
  "The Day Garb",
  "Fashioned Fashion",
  "Wardrobe Spot ",
  "TatteredClothing",
  "The Best",
  "FreshApparel",
  "National Cut",
  "The Haphazard Mode",
  "Enough Apparel",
  "HandClothing",
  "Term Temporal",
  "Captain Fashion",
  "The Coarse",
];

let Fabrics = [
  "Cotton",
  "Denim",
  "Silk",
  "Natural",
  "Felt",
  "Velvet",
  "Rayon",
  "Wool",
  "Satin",
  "Jacqurd",
  "Chiffon",
  "Bazie",
  "Twill",
  "Dimity",
];

let Patterns = [
  "Flame Stitch",
  "Basketweave",
  "Brocade",
  "Checked",
  "Damask",
  "Chevron",
  "Chinoiserie",
  "Floral",
  "Geometric",
  "Harlequin",
  "Ikat",
  "Jacquard",
  "Paisley",
  "Medallion",
  "Khadi Print",
  "Puff Paint",
  "Metallic Paint",
];
const random = (arr) => arr[Math.floor(Math.random() * arr.length)];

let allProducts = [
  {
    name: "Mandarin Collar Rayon All Over Floral Print Grey A-Line Tunic For Women",
    type: "Women Ethnic",
    id: 1,
    sprice: 165,
    aprice: 950,
    rating: 4.6,
    reviews: 69,
    off: 95,
    img: "https://kalamandir.online/static/media/ff1.5f9b1848a7d649ec0e14.webp",
    soldBy: "NDS CREATION",
    details: [
      `Fabric : ${random(Fabrics)}`,
      "Sleeve Length : Three-Quarter Sleeves",
      "Pattern : Embroidered",
      "Combo of : Single",
    ],
  },
  {
    name: "Trendy Pretty Kurtis",
    type: "Women Ethnic",
    id: 1,
    sprice: 410,
    aprice: 460,
    rating: 4.6,
    reviews: 69,
    off: 95,
    img: "https://kalamandir.online/static/media/ee1.9d2bdca8426fcc8b01a5.webp",
    soldBy: "NDS CREATION",
    details: [
      `Fabric : ${random(Fabrics)}`,
      "Sleeve Length : Three-Quarter Sleeves",
      "Pattern : Embroidered",
      "Combo of : Single",
    ],
  },
  {
    name: "Trendy Pretty Kurtis",
    type: "Women Ethnic",
    id: 1,
    sprice: 410,
    aprice: 460,
    rating: 4.6,
    reviews: 69,
    off: 95,
    img: "https://images.meesho.com/images/products/41713416/fef4b_512.jpg",
    soldBy: "NDS CREATION",
    details: [
      `Fabric : ${random(Fabrics)}`,
      "Sleeve Length : Three-Quarter Sleeves",
      "Pattern : Embroidered",
      "Combo of : Single",
    ],
  },
  
];
export { allProducts };
